### PR TITLE
Feature UI main menu

### PR DESCRIPTION
**Pull request by mandynoto**
This implements a scene called MainMenuScene consisting of 3 buttons: Multiplayer, Settings, and Quit.

### CODE REVIEW

**Review by DavidYeLuo — COMMENTED** [review]
1. Name the middle button "Settings button".
2. Stretch each button wider. At least they shouldn't wrap around.
3. Canvas settings: change UI Scale Mode to Scale with Screen Size -> Reference Resolution 1920x1080
     This change will make the UI independent of screen resolution.

Note: I personally not a fan of overriding the camera's skybox. This is because it is likely that we will use a texture instead. The white background is a placeholder for an image. We won't be using that code once we switch. Likely, we won't use the code.

**Comment by DavidYeLuo** [comment]
-> Consider using a big image or panel for a background.

**Comment by DavidYeLuo** [comment]
I merged the change for start menu so make sure to update your branch and move your local changes to the new folder.

**Review by DavidYeLuo — CHANGES_REQUESTED** [review]
Test

**Review by DavidYeLuo — APPROVED** [review]

**Comment by mandynoto** [comment]
> I merged the change for start menu so make sure to update your branch and move your local changes to the new folder.

After trying to rebase on top of develop, I ran into a strange merge conflict. I think I'll redo this task as a precaution.

**Pull request closed without merging**
